src/config/Restrictions.ts, src/diagram/DiagramApp.tsx, src/diagram/DiagramCanvas.tsx, src/function/FunctionCreateVars.ts, src/function/FunctionEditVars.ts, src/function/FunctionGraph.ts, src/function/FunctionRestriction.ts, src/index.tsx, src/interface/ContextInterface.ts, src/interface/SPARQLInterface.ts, src/interface/TransactionInterface.ts, src/panels/ItemPanel.tsx, src/panels/detail/DetailElement.tsx, src/scss/panels/ElementPanel.scss
Closes #61.
Deploy: https://deploy-preview-62--ontographer.netlify.app/
=> Fixing loading of OWL restrictions

.idea/inspectionProfiles/Project_Default.xml, src/function/FunctionCreateVars.ts, src/function/FunctionGraph.ts, src/index.tsx, src/locale/LocaleMain.json, src/main/DiagramCanvas.tsx, src/panels/detail/DetailElement.tsx, src/panels/detail/DetailLink.tsx, src/panels/detail/components/LabelTable.tsx, src/panels/menu/MenuPanelAbout.tsx, src/panels/menu/misc/AboutModal.tsx, src/scss/panels/DetailPanel.scss
Changes: 
* Detail panel improvements
* #72 fix
Deploy: https://deploy-preview-74--ontographer.netlify.app/
=> Detail panel UI

src/function/FunctionGraph.ts, src/main/DiagramCanvas.tsx
* Closes #165.
* Closes #166.
* [JaKl Obchodní rejstřík](https://deploy-preview-167--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-167--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-167--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-167--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1178651091)
* …
=> Fixing #165, #166

src/panels/detail/DetailElement.tsx
* There were some issues in Netlify building the preview - that's why I momentarily returned to draft.
* Closes #163.
* [JaKl Obchodní rejstřík](https://deploy-preview-177--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-177--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-177--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-177--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metad …
=> Issue #163

src/function/FunctionGraph.ts, src/panels/detail/DetailElement.tsx
* Closes #202.
* You may merge this branch.
* [JaKl Obchodní rejstřík](https://deploy-preview-212--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-212--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-212--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-212--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1178651091)
* …
=> Issue #202

src/main/DiagramApp.tsx
* Changes implementation of Keycloak to use Standard flow instead of Implicit flow.
* Tested on server with Implicit flow disabled - that should hopefully mean that it can be disabled on the real server too without issues.
* Closes #197.
* Can be merged right away.
[ML Test](https://deploy-preview-228--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
[Datové fondy VS](https://deploy-preview-228--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
[Marie test](https://deploy-preview-228--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov% …
=> Keycloak Implicit -> Standard flow

src/queries/UpdateConnectionQueries.ts
* Resolves export issues that manifested [here](https://github.com/opendata-mvcr/ssp/pull/212#pullrequestreview-576623494).
* Can be merged right away.
[ML Test](https://deploy-preview-226--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
[Datové fondy VS](https://deploy-preview-226--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
[Marie test](https://deploy-preview-226--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
[mm-test](https://deploy-preview-226--ontographer.netlify.app/?workspace=https:/ …
=> Export issue fix

src/config/Variables.ts, src/datatypes/Cardinality.ts, src/function/FunctionEditVars.ts, src/function/FunctionGetVars.ts, src/interface/ContextInterface.ts, src/interface/JSONInterface.ts, src/interface/SPARQLInterface.ts, src/main/NewLinkModal.tsx
* Can be merged and deleted right away.
* Optimized the startup sequence to limit the number of requests.
* Tests showed about a 20% speed increase and request number decrease by about 10x.
[ML Test](https://deploy-preview-238--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
[Datové fondy VS](https://deploy-preview-238--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
[Marie test](https://deploy-preview-238--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086) …
=> Enhancement - Startup optimization

src/panels/ItemPanel.tsx
* Closes #245.
* [ML test](https://deploy-preview-251--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-251--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-251--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
* [mm-test](https://deploy-preview-251--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/insta …
=> [#245] Window scrolling issue

src/queries/UpdateConnectionQueries.ts
* Closes #242.
* [ML test](https://deploy-preview-250--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-250--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-250--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
* [mm-test](https://deploy-preview-250--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/insta …
=> [#242] Cardinality change issue

src/function/FunctionGraph.ts, src/main/NewLinkModal.tsx
* Closes #239.
* Disallowed creation of generalizations with the same target and source term.
* Fixed an issue where the "loop" for relationships with the same target and source term was not created, which prevented selection (and deletion) of the relationship.
* [ML test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-249--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3% …
=> [#239] "Self loop" issue

src/config/Variables.ts, src/config/logic/RestrictionConfig.ts, src/datatypes/Cardinality.ts, src/function/FunctionGetVars.ts, src/function/FunctionGraph.ts, src/function/FunctionLink.ts, src/interface/JSONInterface.ts, src/panels/detail/DetailLink.tsx
* Closes #241.
* If a non-sensical cardinality (such as 2..1) is detected, ontoGrapher reverts to the default cardinality (0..*).
* [ML test](https://deploy-preview-248--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-248--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-248--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
* …
=> [#241] Cardinality issue

src/queries/UpdateConnectionQueries.ts
* Fixes a bug where numbers would be passed off as IRIs on connection updates.
* [Deploy preview](https://deploy-preview-262--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance1483547911)
=> Urgent connection deletion bug fix

.idea/prettier.xml, src/function/FunctionDraw.ts, src/function/FunctionGraph.ts
* Fixes an issue where property-types related to object-types were not shown in the object-type in Compact view.
* [ML test](https://deploy-preview-265--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1101091271)
* [Datové fondy VS](https://deploy-preview-265--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1153182747)
* [Marie test](https://deploy-preview-265--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-530560086)
* [mm-test](https://deploy-preview-265--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%B …
=> No properties in compact view fix

src/function/FunctionEditVars.ts, src/queries/update/UpdateConnectionQueries.ts, src/queries/update/UpdateMiscQueries.ts
* Closes #269.
* [Veřejné rejstříky](https://deploy-preview-270--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-224258741)
* [eSbírka](https://deploy-preview-270--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-1326236660)
* [Datový model OFN číselníků a statistických klasifikací](https://deploy-preview-270--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kontext/instance-2083940323)
* [Karel test](https://deploy-preview-270--ontographer.netlify.app/?workspace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/pracovn%C3%AD-prostor/pojem/metadatov%C3%BD-kon …
=> Urgent generalization saving error fix

.gitignore, src/interface/TransactionInterface.ts, src/main/NewLinkModal.tsx, src/panels/ItemPanel.tsx
=> Issue #268 #271 fix

src/panels/modal/ModalRemoveItem.tsx
=> Issue #285

src/config/Variables.ts, src/function/FunctionCreateVars.ts, src/function/FunctionDiagram.ts, src/function/FunctionGraph.ts, src/locale/cschangelog.ts, src/locale/enchangelog.ts, src/main/DiagramApp.tsx, src/panels/MenuPanel.tsx, src/panels/diagram/DiagramAdd.tsx, src/panels/menu/MenuPanelSwitchRepresentation.tsx, src/queries/get/InitQueries.ts, src/queries/update/UpdateMiscQueries.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion2.ts
=> Representation state for each diagram

package-lock.json, package.json, src/locale/cshelp.ts, src/locale/enhelp.ts, src/main/DiagramCanvas.tsx
* Can be merged and deleted right away.
* Closes #231.
* Closes #206 (Delete key hides selected elements).
=> Ctrl+A and Delete hotkeys

src/config/Environment.ts, src/function/FunctionGetVars.ts, src/index.tsx, src/interface/TransactionInterface.ts, src/locale/cs.ts, src/locale/en.ts, src/main/App.tsx, src/panels/MenuPanel.tsx, src/panels/ValidationPanel.tsx, src/panels/diagram/DiagramTab.tsx, src/panels/element/VocabularySelector.tsx
* Added an AUTHENTICATION environment variable that disables (enables) Keycloak integration for the purposes of the prepared [demo](https://bindeali.github.io/ontographer-demo/).
* Minor language fixes.
=> Authentication environment variable addition

src/function/FunctionEditVars.ts, src/panels/modal/ModalRemoveItem.tsx, src/panels/modal/ModalRemoveReadOnlyItem.tsx, src/queries/update/UpdateMiscQueries.ts
* Deals with issue mentioned in the first paragraph in [my comment](https://github.com/opendata-mvcr/ontoGrapher/issues/291#issuecomment-876451053) to issue #291 (see mentioned comment for details).
=> Part of #291

src/queries/update/UpdateConnectionQueries.ts
=> Issue #298

src/function/FunctionCache.ts, src/locale/cs.ts, src/locale/en.ts, src/panels/ItemPanel.tsx, src/panels/detail/components/connections/ConnectionCache.tsx, src/panels/modal/ModalRemoveItem.tsx, src/scss/components/ConnectionList.scss, src/scss/components/ModalRemoveItem.scss, src/scss/style.scss
* Closes #291 (Implements a warning message whenever read-only undeleteable connections with a term about to be deleted are detected, along with a listing of those connections).
=> Issue #291

src/main/App.tsx, src/panels/ItemPanel.tsx, src/panels/detail/DetailElement.tsx, src/panels/detail/DetailLink.tsx, src/scss/panels/DetailPanel.scss
* Fixed an issue where an empty read-only vocabulary would still show up on startup.
* Fixed detail panel styling so that scrolling is properly implemented.
=> Fix minor issues

src/components/modals/CreationModals.tsx, src/components/modals/NewLinkModal.tsx, src/function/FunctionDraw.ts, src/main/DiagramCanvas.tsx, src/panels/detail/DetailElement.tsx, src/panels/detail/DetailLink.tsx, src/scss/style.scss
* Fixes issues arising from #300, such as:
* The link creation modal not automatically focusing on the label inputs when creating a new relationship in Compact view.
* The element being deselected on creation of a new instrinsic trope.
* Crash on selecting a generalization in Compact view.
* The link creation modal selecting all elements when active.
=> Fix issues with #300

src/components/modals/NewElemForm.tsx, src/components/modals/NewElemModal.tsx, src/components/modals/NewLinkModal.tsx, src/panels/element/PackageItem.tsx, src/scss/components/ConnectionList.scss
* Closes #309.
* Closes #307.
* Closes #306.
* Closes #305.
=> Fix issues detected in the Demo

.idea/prettier.xml, .idea/runConfigurations/start.xml, src/config/Variables.ts, src/config/logic/RestrictionConfig.ts, src/datatypes/Restriction.ts, src/function/FunctionCreateVars.ts, src/function/FunctionLink.ts, src/function/FunctionRestriction.ts, src/main/App.tsx, src/panels/detail/DetailLink.tsx, src/queries/get/FetchQueries.ts, src/queries/get/InitQueries.ts, src/queries/update/UpdateConnectionQueries.ts, src/queries/update/UpdateMiscQueries.ts, src/queries/update/legacy/FinishUpdatingLegacyWorkspaceQueries.ts, src/queries/update/legacy/UpdateLegacyWorkspaceQueries.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion2.ts
=> Issue #294

src/components/modals/NewElemModal.tsx, src/config/Variables.ts
=> Issue #315

src/queries/QueryBuilder.ts, src/queries/update/UpdateConnectionQueries.ts, src/queries/update/UpdateLinkQueries.ts
* Solves [AL-#63](https://github.com/opendata-mvcr/sgov-assembly-line/issues/63).
* Solves [AL-#62](https://github.com/opendata-mvcr/sgov-assembly-line/issues/62).
=> Issues AL-#62 AL-63

src/config/Variables.ts, src/function/FunctionDraw.ts, src/panels/DetailPanel.tsx, src/queries/update/UpdateElementQueries.ts
* Closes #329 - Display labels are now saved as dc:title also.
* Fixed an issue where the display label didn't change for terms.
=> Issue #329

src/config/Variables.ts, src/config/logic/RepresentationConfig.ts, src/datatypes/CacheSearchResults.ts, src/function/FunctionCache.ts, src/function/FunctionCreateVars.ts, src/function/FunctionEditVars.ts, src/panels/element/SearchTerm.tsx, src/panels/element/VocabularyFolder.tsx, src/panels/modal/ModalRemoveReadOnlyConcept.tsx, src/queries/get/CacheQueries.ts, src/queries/get/FetchQueries.ts, src/queries/get/InitQueries.ts
* Closes #334 - the number of terms ("x/y terms" label in the left panel for read-only vocabularies) now accurately reflects the actual number in both full and compact representations.
=> Issue #334

src/function/FunctionEditVars.ts, src/function/FunctionElem.ts, src/main/App.tsx, src/main/DiagramCanvas.tsx, src/panels/VocabularyPanel.tsx, src/panels/element/SearchTerm.tsx
* Closes #335.
* The cache search is now correctly refreshing on removal or addition of a cache term.
=> Cache search visibility fix

src/function/FunctionGetVars.ts, src/queries/get/InitQueries.ts, src/queries/update/UpdateDiagramQueries.ts, src/queries/update/UpdateReconstructAppContext.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion4.ts
* Changed the workspace architecture updates to conform to changes in the architecture (retained older architecture compatibility).
=> Milestone 1a - workspace architecture changes

src/panels/modal/ModalRemoveDiagram.tsx, src/queries/get/InitQueries.ts, src/queries/update/UpdateDiagramQueries.ts
* Solves issue mentioned in [this comment](https://github.com/opendata-mvcr/ssp/pull/325/files?diff=split&w=0#r760038272).
* Solves issue where refresh on a workspace with one empty diagram produces two diagrams.
=> Milestone 1a - correction & fix

src/config/Variables.ts, src/function/FunctionCreateVars.ts, src/function/FunctionEditVars.ts, src/function/FunctionGetVars.ts, src/main/App.tsx, src/panels/diagram/DiagramAdd.tsx, src/queries/get/InitQueries.ts, src/queries/update/UpdateDiagramQueries.ts, src/queries/update/UpdateElementQueries.ts, src/queries/update/UpdateLinkQueries.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion2.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion4.ts
* Implemented suggestions from the [suggestion PR](https://github.com/opendata-mvcr/ssp/pull/325/files/7a7167b29a5cb9e55b613c123b4315252075bd21#diff-2f01701eb4737f32b49446b0a098c336ba445e276713486249d11c1e5c8c024c).
* Fixed an issue where a diagram wouldn't be selected on workspace open.
* Refactoring.
* Note: Already existing diagram and link IRIs won't be changed for compatibility reasons.
_These appear on diagram creation._
=> Milestone1a - Type & diagram fixes

src/config/Variables.ts, src/function/FunctionCreateVars.ts, src/main/App.tsx, src/queries/get/InitQueries.ts, src/queries/update/UpdateDiagramQueries.ts, src/queries/update/UpdateElementQueries.ts, src/queries/update/UpdateLinkQueries.ts
* Fixes an issue where a diagram wouldn't initialize in new workspaces.
* Added support for diagrams having IRIs different to the graph they are in.
=> Milestone 1a - support different diagram IRIs and graphs

src/queries/get/CacheQueries.ts, src/scss/components/ConnectionList.scss
=> Issue #362

src/function/FunctionCreateVars.ts, src/function/FunctionEditVars.ts, src/function/FunctionGraph.ts, src/interface/ContextInterface.ts, src/panels/menu/modal/SaveDiagramsModal.tsx, src/panels/modal/ModalRemoveConcept.tsx, src/panels/modal/ModalRemoveReadOnlyConcept.tsx
* Resolves [#AL-74](https://github.com/opendata-mvcr/sgov-assembly-line/issues/74).
* Resolves #376.
* Unfortunately yet another PR that can only really be tested after publishing.
=> Fix loading issues

src/components/modals/CreationModals.tsx, src/components/modals/NewLinkModal.tsx, src/function/FunctionElem.ts, src/function/FunctionLink.ts
* Closes #373.
* During creation of **any** term (i.e. explicitly with right click or implicitly with adding new trope in the detail panel / creating a relationship type with a new Compact relationship) no **unrelated** terms should appear on the canvas.
* If the term created is a relationship type / intrinsic trope type in compact mode, **no** terms should appear on the canvas.
=> Issue #373

src/function/FunctionGraph.ts
=> Issue #396

src/panels/VocabularyPanel.tsx
=> Issue #398

src/queries/update/UpdateConnectionQueries.ts
* Closes #402.
* **Testing**: Create/edit relations and see that they do not push duplicate restrictions to the DB.
=> Issue #402

Dockerfile
Fixes issues with building and deploying the app.
=> Docker deployment fix

src/config/logic/RestrictionConfig.ts, src/queries/update/UpdateConnectionQueries.ts
=> Issue #424

src/config/Variables.ts, src/function/FunctionCreateVars.ts, src/function/FunctionElem.ts, src/interface/ContextInterface.tsx, src/panels/diagram/DiagramAdd.tsx, src/panels/diagram/DiagramTab.tsx, src/queries/get/InitQueries.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion2.ts, src/queries/update/legacy/UpdateLegacyWorkspaceToVersion4.ts
=> Issue #428

src/panels/detail/components/element/DetailElementDescriptionCard.tsx
=> Issue #368

src/function/FunctionElem.ts
=> Issue #399

src/queries/get/InitQueries.ts, src/queries/update/UpdateElementQueries.ts
* Prevents [AL-#111](https://github.com/opendata-mvcr/sgov-assembly-line/issues/111) from happening again (the solution includes fixing the existing data too).
=> Issue AL-#111

src/queries/get/InitQueries.ts, src/queries/update/UpdateElementQueries.ts
* Works on [AL-#113](https://github.com/opendata-mvcr/sgov-assembly-line/issues/113).
=> Issue AL-113

src/interface/ContextInterface.tsx
* If an OG-style/owl:Restriction relationship linked to a non-existent relationship type term is detected, the relationship is discarded instead of a crash.
=> Checking for links connected to non-existent (relationship) types

src/panels/VocabularyPanel.tsx
* Closes [AL-110](https://github.com/opendata-mvcr/sgov-assembly-line/issues/110).
=> Issue AL-#110

package-lock.json, src/function/FunctionCreateElem.ts, src/function/FunctionElem.ts, src/function/FunctionGraph.ts, src/panels/detail/components/IntrinsicTropeTableSelect.tsx, src/queries/update/UpdateDiagramQueries.ts
* Fixes an issue where intrinsic tropes created in Compact Mode wouldn't show up in Full Mode ([Issue AL-116](https://github.com/opendata-mvcr/sgov-assembly-line/issues/116))
* Fixes an issue where already "used" intrinsic tropes would show up in the select element in a Compact Mode term's Detail Panel.
=> Fix issue AL-116

.gitignore, src/function/FunctionCreateElem.ts, src/function/FunctionElem.ts, src/queries/get/FetchQueries.ts
* Works on [AL-122](https://github.com/opendata-mvcr/sgov-assembly-line/issues/122).
=> Issue AL-122

src/datatypes/CacheSearchResults.ts, src/function/FunctionEditVars.ts, src/function/FunctionElem.ts, src/main/App.tsx, src/panels/VocabularyPanel.tsx, src/queries/get/CacheQueries.ts
* Fixed an issue where Full read-only turns would show up in search even in compact mode.
* Fixed an issue where a term would remain selected even when opening another term.
* Mildly refactored drag&drop function.
=> Minor fixes

package-lock.json, src/function/FunctionDraw.ts, src/panels/menu/modal/ExportModal.tsx, src/panels/menu/modal/export/ExportModalImage.tsx, src/panels/menu/modal/export/ExportModalTerms.tsx, src/panels/menu/modal/export/ExportTermsCSV.ts, src/panels/menu/modal/export/ExportTermsText.ts
* Fixes issues described in a [comment on Issue AL-129](https://github.com/opendata-mvcr/sgov-assembly-line/issues/129#issuecomment-1495838241).
* Fixes issue where attributes for event type terms would be drawn out of term bounds.
* Includes [this PR](https://github.com/opendata-mvcr/ontoGrapher/pull/479).
=> Issue AL-129: Term export fixes
